//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfExternalServiceApplication.InternalServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InternalServiceReference.IInternalService")]
    public interface IInternalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalService/GetMochi", ReplyAction="http://tempuri.org/IInternalService/GetMochiResponse")]
        string GetMochi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalService/GetMochi", ReplyAction="http://tempuri.org/IInternalService/GetMochiResponse")]
        System.Threading.Tasks.Task<string> GetMochiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalService/GetMochiIceCreamByFlavor", ReplyAction="http://tempuri.org/IInternalService/GetMochiIceCreamByFlavorResponse")]
        string GetMochiIceCreamByFlavor(string flavor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalService/GetMochiIceCreamByFlavor", ReplyAction="http://tempuri.org/IInternalService/GetMochiIceCreamByFlavorResponse")]
        System.Threading.Tasks.Task<string> GetMochiIceCreamByFlavorAsync(string flavor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInternalServiceChannel : WcfExternalServiceApplication.InternalServiceReference.IInternalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InternalServiceClient : System.ServiceModel.ClientBase<WcfExternalServiceApplication.InternalServiceReference.IInternalService>, WcfExternalServiceApplication.InternalServiceReference.IInternalService {
        
        public InternalServiceClient() {
        }
        
        public InternalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InternalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMochi() {
            return base.Channel.GetMochi();
        }
        
        public System.Threading.Tasks.Task<string> GetMochiAsync() {
            return base.Channel.GetMochiAsync();
        }
        
        public string GetMochiIceCreamByFlavor(string flavor) {
            return base.Channel.GetMochiIceCreamByFlavor(flavor);
        }
        
        public System.Threading.Tasks.Task<string> GetMochiIceCreamByFlavorAsync(string flavor) {
            return base.Channel.GetMochiIceCreamByFlavorAsync(flavor);
        }
    }
}
